### ISSUE TITLE
Example of NIP04

### ISSUE THREAD

**Issue by nicognaW** [anasfik/nostr#4]
Hi, I tried to implement [NIP04](https://github.com/nostr-protocol/nips/blob/master/04.md) using dart & `dart_nostr` (great job BTW), but I didn't find the correct encryption implementations, could you please provide an example of sending encrypted DM with `dart_nostr`?

**Comment by anasfik** [comment]
You can make NIP 04 eb=vents and manage sending/receiving them, but I'm sorry to say that at this point, you will need to do all encrypting stuff manually, this is on the roadmap of todos of this package so it will have it's own method and it's encrypting tool jit included in the package.
